# pLLM CLI Configuration Example
# Copy this to ~/.pllm.yaml or use --config flag

# Database connection (for direct access when running on server)
database:
  url: "postgres://pllm:pllm@localhost:5432/pllm?sslmode=disable"

# API configuration (for remote access)
api:
  url: "https://your-pllm-instance.com"
  key: "your-api-key-here"

# Output preferences
output:
  json: false
  verbose: false

# Default limits
limits:
  page_size: 50
  timeout: 30