# Dex configuration for pLLM authentication (Docker environment)
# Dex advertises PUBLIC URL as issuer (for browsers), backend connects via INTERNAL URL
issuer: http://localhost:5556/dex

storage:
  type: postgres
  config:
    host: postgres
    port: 5432
    database: dex
    user: pllm
    password: pllm
    ssl:
      mode: disable

web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']

grpc:
  addr: 0.0.0.0:5557

telemetry:
  http: 0.0.0.0:5558

# Static clients for pLLM
staticClients:
  # Web UI client
  - id: pllm-web
    name: "pLLM Web UI"
    secret: pllm-web-secret
    redirectURIs:
      - "http://localhost:8080/ui/callback"
      - "http://localhost:8080/callback"
      - "http://localhost:3000/callback"
      - "http://localhost:5173/callback"
    grantTypes:
      - authorization_code
      - refresh_token
    scopes:
      - openid
      - profile
      - email
      - groups
      - offline_access
    # Skip the approval screen when possible
    trustedPeers:
      - pllm-web

  # Swagger UI client
  - id: pllm-swagger
    name: "pLLM Swagger UI"
    secret: pllm-swagger-secret
    redirectURIs:
      - "http://localhost:8080/swagger/oauth2-redirect.html"
    grantTypes:
      - authorization_code
      - implicit
    scopes:
      - openid
      - profile
      - email

  # Backend service client (for service-to-service auth)
  - id: pllm-backend
    name: "pLLM Backend Service"
    secret: pllm-backend-secret
    public: false

# OAuth2 connectors
connectors:
  # GitHub OAuth
  - type: github
    id: github
    name: GitHub
    config:
      clientID: $GITHUB_CLIENT_ID
      clientSecret: $GITHUB_CLIENT_SECRET
      redirectURI: http://localhost:5556/dex/callback
      scopes:
        - user:email
        - read:user
        - read:org

  # Google OAuth
  - type: google
    id: google
    name: Google
    config:
      clientID: $GOOGLE_CLIENT_ID
      clientSecret: $GOOGLE_CLIENT_SECRET
      redirectURI: http://localhost:5556/dex/callback

  # Microsoft OAuth
  - type: microsoft
    id: microsoft
    name: Microsoft
    config:
      clientID: $MICROSOFT_CLIENT_ID
      clientSecret: $MICROSOFT_CLIENT_SECRET
      redirectURI: http://localhost:5556/dex/callback
      tenant: organizations

# Static users for development/testing
enablePasswordDB: true

staticPasswords:
  # Admin user
  - email: "admin@pllm.local"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password: admin
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    groups:
      - "admin"
      - "developers"

  # Test user with limited access
  - email: "user@pllm.local"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password: user
    username: "testuser"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5467"
    groups:
      - "users"

# Token expiry settings
expiry:
  deviceRequests: "5m"
  signingKeys: "6h"
  idTokens: "24h"
  refreshTokens:
    reuseInterval: "3s"
    validIfNotUsedFor: "2160h" # 90 days

# Frontend configuration
frontend:
  theme: "light"
  issuer: "pLLM Gateway"

# OAuth2 settings
oauth2:
  # Skip the approval screen for trusted clients
  skipApprovalScreen: true
  # Always show the approval screen for these response types
  # alwaysShowLoginScreen: false
  passwordConnector: local