// Central mapping of UI icon names to Iconify Solar icon identifiers.
// Usage: import { icons } from '@/lib/icons'; <Icon icon={icons.dashboard} />

export const icons = {
  // Navigation
  dashboard: 'solar:widget-bold-duotone',
  chat: 'solar:chat-round-dots-linear',
  models: 'solar:cpu-bolt-linear',
  routes: 'solar:routing-2-linear',
  keys: 'solar:key-minimalistic-linear',
  teams: 'solar:users-group-rounded-linear',
  users: 'solar:user-linear',
  budget: 'solar:wallet-money-linear',
  auditLogs: 'solar:document-text-linear',
  guardrails: 'solar:shield-check-linear',
  settings: 'solar:settings-linear',

  // Actions
  add: 'solar:add-circle-linear',
  plus: 'solar:add-square-linear',
  edit: 'solar:pen-2-linear',
  delete: 'solar:trash-bin-trash-linear',
  close: 'solar:close-circle-linear',
  search: 'solar:magnifer-linear',
  filter: 'solar:filter-linear',
  refresh: 'solar:refresh-linear',
  copy: 'solar:copy-linear',
  send: 'solar:plain-2-linear',
  download: 'solar:download-minimalistic-linear',
  upload: 'solar:upload-minimalistic-linear',
  moreHorizontal: 'solar:menu-dots-bold',
  moreVertical: 'solar:menu-dots-vertical-bold',

  // Navigation / Chevrons
  chevronRight: 'solar:alt-arrow-right-linear',
  chevronLeft: 'solar:alt-arrow-left-linear',
  chevronDown: 'solar:alt-arrow-down-linear',
  chevronUp: 'solar:alt-arrow-up-linear',
  chevronsUpDown: 'solar:sort-vertical-linear',
  arrowUp: 'solar:arrow-up-linear',
  arrowDown: 'solar:arrow-down-linear',
  arrowLeft: 'solar:arrow-left-linear',
  arrowRight: 'solar:arrow-right-linear',
  arrowUpDown: 'solar:sort-linear',
  externalLink: 'solar:square-top-down-linear',

  // Status
  check: 'solar:check-circle-bold',
  warning: 'solar:danger-triangle-linear',
  error: 'solar:close-circle-bold',
  info: 'solar:info-circle-linear',
  active: 'solar:check-circle-bold',

  // Misc
  sun: 'solar:sun-2-linear',
  moon: 'solar:moon-linear',
  eye: 'solar:eye-linear',
  eyeOff: 'solar:eye-closed-linear',
  power: 'solar:power-linear',
  logout: 'solar:logout-2-linear',
  book: 'solar:book-minimalistic-linear',
  github: 'solar:code-square-linear',
  mail: 'solar:inbox-linear',
  loader: 'solar:refresh-linear',
  trendingUp: 'solar:graph-up-linear',
  trendingDown: 'solar:graph-down-linear',
  minus: 'solar:minus-circle-linear',
  shield: 'solar:shield-linear',
  user: 'solar:user-circle-linear',
  calendar: 'solar:calendar-linear',
  clock: 'solar:clock-circle-linear',
  link: 'solar:link-linear',
  code: 'solar:code-linear',
  play: 'solar:play-linear',
  stop: 'solar:stop-linear',
  image: 'solar:gallery-linear',
  file: 'solar:file-linear',
  folder: 'solar:folder-linear',
  home: 'solar:home-2-linear',
  star: 'solar:star-linear',
  heart: 'solar:heart-linear',
  bolt: 'solar:bolt-linear',
  lock: 'solar:lock-linear',
  unlock: 'solar:lock-unlocked-linear',
  globe: 'solar:global-linear',
  terminal: 'solar:command-linear',
  layers: 'solar:layers-linear',
  maximize: 'solar:maximize-linear',
  minimize: 'solar:minimize-linear',
  mcp: 'solar:plug-circle-linear',
  registry: 'solar:book-bookmark-linear',
  agent: 'solar:bot-linear',
  skill: 'solar:diploma-linear',
  prompt: 'solar:document-text-linear',
  deployment: 'solar:cloud-linear',
  rocket: 'solar:rocket-linear',
} as const;

export type IconName = keyof typeof icons;
