apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pllm.fullname" . }}
  labels:
    {{- include "pllm.labels" . | nindent 4 }}
data:
  # Authentication configuration
  # Backend OIDC validation (internal service URL)
  dex-issuer: {{ .Values.pllm.config.auth.dex.issuer | default (printf "http://%s-dex.%s.svc.cluster.local:5556/dex" (include "pllm.fullname" .) .Release.Namespace) }}
  # Frontend OAuth flows (public URL)  
  dex-public-issuer: {{ .Values.pllm.config.auth.dex.publicIssuer | default .Values.pllm.config.auth.dex.issuer | default (printf "http://%s-dex.%s.svc.cluster.local:5556/dex" (include "pllm.fullname" .) .Release.Namespace) }}
  dex-client-id: {{ .Values.pllm.config.auth.dex.clientId }}

  # Provider configuration
  bedrock-region: {{ .Values.pllm.config.providers.bedrock.region }}

  # Rate limiting
  rate-limit-enabled: {{ .Values.pllm.config.rateLimit.enabled | quote }}
  rate-limit-rpm: {{ .Values.pllm.config.rateLimit.rpm | quote }}
  rate-limit-rph: {{ .Values.pllm.config.rateLimit.rph | quote }}

  # Logging
  log-level: {{ .Values.pllm.config.logging.level }}
  log-format: {{ .Values.pllm.config.logging.format }}

  # Realtime WebSocket configuration
  realtime-enabled: {{ .Values.pllm.config.realtime.enabled | quote }}
  realtime-max-sessions: {{ .Values.pllm.config.realtime.maxSessions | quote }}
  realtime-session-timeout: {{ .Values.pllm.config.realtime.sessionTimeout | quote }}
  realtime-cleanup-interval: {{ .Values.pllm.config.realtime.cleanupInterval | quote }}
  realtime-max-connections-per-ip: {{ .Values.pllm.config.realtime.maxConnectionsPerIP | quote }}
  realtime-max-message-size: {{ .Values.pllm.config.realtime.maxMessageSize | quote }}
  realtime-read-buffer-size: {{ .Values.pllm.config.realtime.readBufferSize | quote }}
  realtime-write-buffer-size: {{ .Values.pllm.config.realtime.writeBufferSize | quote }}
  realtime-session-store-type: {{ .Values.pllm.config.realtime.sessionStoreType | quote }}
  realtime-redis-prefix: {{ .Values.pllm.config.realtime.redisPrefix | quote }}