apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pllm.fullname" . }}
  labels:
    {{- include "pllm.labels" . | nindent 4 }}
type: Opaque
data:
  # Database URL (full connection string)
  database-url: {{ if .Values.postgresql.enabled }}{{ printf "postgres://%s:%s@%s-postgresql:%d/%s?sslmode=disable" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "pllm.fullname" .) 5432 .Values.postgresql.auth.database | b64enc }}{{ else }}{{ .Values.pllm.secrets.databaseUrl | b64enc }}{{ end }}
  
  # Redis URL (full connection string)
  redis-url: {{ if .Values.redis.enabled }}{{ printf "redis://:%s@%s-redis-master:%d/%d" .Values.redis.auth.password (include "pllm.fullname" .) 6379 0 | b64enc }}{{ else }}{{ .Values.pllm.secrets.redisUrl | b64enc }}{{ end }}
  
  # JWT secret
  jwt-secret: {{ required "JWT secret is required" .Values.pllm.secrets.jwtSecret | b64enc }}
  
  # Master key
  master-key: {{ required "Master key is required" .Values.pllm.secrets.masterKey | b64enc }}
  
  # Dex client secret
  dex-client-secret: {{ if .Values.dex.enabled }}{{ index .Values.dex.config.staticClients 0 "secret" | b64enc }}{{ else }}{{ .Values.pllm.secrets.dexClientSecret | b64enc }}{{ end }}
  
  # Provider API keys (optional)
  {{- if .Values.pllm.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.pllm.secrets.openaiApiKey | b64enc }}
  {{- end }}
  
  {{- if .Values.pllm.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.pllm.secrets.anthropicApiKey | b64enc }}
  {{- end }}
  
  {{- if .Values.pllm.secrets.azureApiKey }}
  azure-api-key: {{ .Values.pllm.secrets.azureApiKey | b64enc }}
  {{- end }}
  
  {{- if .Values.pllm.secrets.bedrockAccessKeyId }}
  bedrock-access-key-id: {{ .Values.pllm.secrets.bedrockAccessKeyId | b64enc }}
  {{- end }}
  
  {{- if .Values.pllm.secrets.bedrockSecretAccessKey }}
  bedrock-secret-access-key: {{ .Values.pllm.secrets.bedrockSecretAccessKey | b64enc }}
  {{- end }}