version: "3.8"

services:
  dex:
    image: ghcr.io/dexidp/dex:v2.38.0
    container_name: pllm-dex
    restart: unless-stopped
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    ports:
      - "5556:5556" # Web
      - "5557:5557" # gRPC
      - "5558:5558" # Metrics
    volumes:
      - ./dex/config.yaml:/etc/dex/config.yaml:ro
      - dex-data:/var/dex
    environment:
      # OAuth2 provider credentials (set these in .env)
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID:-}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET:-}
    depends_on:
      - dex-postgres
    networks:
      - pllm-network

  dex-postgres:
    image: postgres:15-alpine
    container_name: pllm-dex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dex
      POSTGRES_PASSWORD: dex_password
      POSTGRES_DB: dex
    volumes:
      - dex-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Different port to avoid conflict with main postgres
    networks:
      - pllm-network

volumes:
  dex-data:
  dex-postgres-data:

networks:
  pllm-network:
    external: true
