# Minikube local development values
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: pllm.local
      paths:
        - path: /
          pathType: Prefix

# Dex configuration for Minikube
dex:
  enabled: true
  # Disable separate Dex ingress - use main ingress with /dex path
  ingress:
    enabled: false
  config:
    issuer: "http://pllm-dex:5556/dex"
    staticClients:
      - id: pllm
        redirectURIs:
          - 'http://pllm.local/auth/callback'
          - 'http://pllm.local/ui/callback'
          - 'http://pllm.local/ui/silent-renew'
        name: 'PLLM'
        secret: pllm-client-secret

# PLLM configuration for Minikube  
pllm:
  secrets:
    jwtSecret: "demo-jwt-secret-minikube"
    masterKey: "sk-master-demo-minikube"
    dexClientSecret: "pllm-client-secret"
  config:
    auth:
      dex:
        # Backend uses internal service URL for OIDC validation
        issuer: "http://pllm-dex:5556/dex"
        # Frontend uses external domain with /dex path for OAuth flows
        publicIssuer: "http://pllm.local/dex"
        redirectUrl: "http://pllm.local/auth/callback"