# Example production values for PLLM
# Copy this file to values-prod.yaml and customize for your environment

# Number of PLLM replicas
replicaCount: 2

# PLLM application configuration
pllm:
  # REQUIRED: Set your secrets here
  secrets:
    # REQUIRED: JWT secret for token signing (generate with: openssl rand -hex 32)
    jwtSecret: "your-super-secret-jwt-key-here-change-me"
    # REQUIRED: Master key for admin access (generate with: openssl rand -hex 32)
    masterKey: "sk-master-your-production-master-key-here"
    
    # Provider API keys (set the ones you need)
    openaiApiKey: "sk-your-openai-api-key-here"
    anthropicApiKey: "sk-ant-your-anthropic-api-key-here"
    azureApiKey: ""  # Leave empty if not using
    bedrockAccessKeyId: ""  # Leave empty if not using
    bedrockSecretAccessKey: ""  # Leave empty if not using

# Ingress configuration (recommended for production)
ingress:
  enabled: true
  className: nginx  # or your ingress class
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod  # if using cert-manager
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/rate-limit: "100"
  hosts:
    - host: pllm.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: pllm-tls
      hosts:
        - pllm.yourdomain.com

# Auto-scaling (recommended for production)
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Resource limits (recommended for production)
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

# Dex SSO configuration
dex:
  enabled: true
  config:
    # IMPORTANT: This is automatically set by the Helm chart
    issuer: ""  # Will be set to: http://pllm-dex.{namespace}.svc.cluster.local:5556/dex
    staticClients:
      - id: pllm
        redirectURIs:
          - 'https://pllm.yourdomain.com/auth/callback'  # Update with your domain
          - 'http://localhost:3000/auth/callback'  # For local development
        name: 'PLLM'
        secret: pllm-client-secret-change-me  # Change this!
    connectors:
      # Example: GitHub OAuth
      - type: github
        id: github
        name: GitHub
        config:
          clientID: your-github-oauth-client-id
          clientSecret: your-github-oauth-client-secret
          redirectURI: https://pllm.yourdomain.com/dex/callback
          orgs:
            - name: your-github-org  # Restrict to specific org
      
      # Example: Google OAuth  
      # - type: oidc
      #   id: google
      #   name: Google
      #   config:
      #     issuer: https://accounts.google.com
      #     clientID: your-google-client-id.googleusercontent.com
      #     clientSecret: your-google-client-secret
      #     redirectURI: https://pllm.yourdomain.com/dex/callback

# Database (PostgreSQL) - production settings
postgresql:
  enabled: true
  auth:
    username: pllm
    password: "change-this-postgresql-password"
    database: pllm
  primary:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: ""  # Use default storage class
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m

# Redis - production settings  
redis:
  enabled: true
  auth:
    enabled: true
    password: "change-this-redis-password"
  master:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""  # Use default storage class
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 200m

# Monitoring (enable if you have Prometheus)
serviceMonitor:
  enabled: false  # Set to true if you have Prometheus operator
  labels:
    prometheus: kube-prometheus
  interval: 30s