global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PLLM Gateway metrics
  - job_name: 'pllm-gateway'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['pllm:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'pllm-gateway'